### ISSUE TITLE
sentiment.py fails

### ISSUE THREAD

**Issue by ictinc** [shirosaidev/stocksight#8]
Hi there,
I would really like to try out you program. I have everything installed as described but after running;
`python sentiment.py -k TSLA,'Elon Musk',Musk,Tesla --debug`

I receive the following error:

`2019-02-02 02:19:54,186 [WARNING][stocksight] Exception: exception caused by:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - '/home/user/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************

Traceback (most recent call last):
  File "sentiment.py", line 796, in <module>
    stream.filter(track=keywords, languages=['en'])
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 453, in filter
    self._start(is_async)
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 368, in _start
    self._run()
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 300, in _run
    six.reraise(*exc_info)
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 269, in _run
    self._read_loop(resp)
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 331, in _read_loop
    self._data(next_status_obj)
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 303, in _data
    if self.listener.on_data(data) is False:
  File "sentiment.py", line 127, in on_data
    tokens = nltk.word_tokenize(text_for_tokens)
  File "/home/user/.local/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 143, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/user/.local/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 104, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/home/user/.local/lib/python2.7/site-packages/nltk/data.py", line 868, in load
    opened_resource = _open(resource_url)
  File "/home/user/.local/lib/python2.7/site-packages/nltk/data.py", line 993, in _open
    return find(path_, path + ['']).open()
  File "/home/user/.local/lib/python2.7/site-packages/nltk/data.py", line 699, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - '/home/user/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************`

I have issued:
`pip install nltk`
and even issued:
`apt-get install python-numpy python-nltk`

And tried NLTK manually:

`
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> Import nltk
  File "<stdin>", line 1
    Import nltk
              ^
SyntaxError: invalid syntax
`
I'm not sure what I'm missing here, and hope you can help me get everything running as it's supposed to.
I'm running Ubuntu 18.04 with the latest updates.
Kind regards,
Ronald.

**Comment by AshyIsMe** [comment]
It looks like you have a capital I in `Import ntlk`.

Try the following manually being careful to keep the cases the same:

```
import nltk
nltk.download('punkt')

```

If that succeeds then you should be able to run `sentiment.py` as you were trying previously.

(Note: I'm not the author of this project but was testing it recently and hit the same issue)

**Comment by ictinc** [comment]
Thank you very much for your repsonse. This seems to have solved everything. :)

**Comment by shirosaidev** [comment]
thanks @AshyIsMe , @ictinc Python 3.x is required
https://github.com/shirosaidev/stocksight#requirements
